[package]
name = "entity"
version = "0.2.0"
edition = "2021"
publish = false

[lib]
name = "entity"
path = "src/lib.rs"

[dependencies]
axum-login = "0.12"
sea-orm = { version = "0.12" }
strum = "0.25"

[dependencies.serde]
version = "1"
features = [ "derive" ]