apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: /home/vezir/go/bin/kompose convert -f stack.yml
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: backend
  name: backend
spec:
  ports:
    - name: "8000"
      port: 8000
      targetPort: 8000
  selector:
    io.kompose.service: backend
