apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /home/vezir/go/bin/kompose convert -f stack.yml
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: mailhog
  name: mailhog
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mailhog
  template:
    metadata:
      annotations:
        kompose.cmd: /home/vezir/go/bin/kompose convert -f stack.yml
        kompose.version: 1.32.0 (HEAD)
      labels:
        io.kompose.network/ticketing-ticketing-net: "true"
        io.kompose.service: mailhog
    spec:
      containers:
        - image: mailhog/mailhog:latest
          name: mailhog
          ports:
            - containerPort: 1025
              hostPort: 1025
            - containerPort: 8025
              hostPort: 8025
      hostname: mailhog
      restartPolicy: Always
