apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mariadb-init-storage
provisioner: kubernetes.io/no-provisioner
reclaimPolicy: Retain
volumeBindingMode: Immediate

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: mariadb-init-pv
spec:
  capacity:
    storage: 1Mi
  volumeMode: Filesystem
  accessModes:
    - ReadOnlyMany
  storageClassName: mariadb-init-storage
  local:
    path: /data/mariadb
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: node-role.kubernetes.io/worker
              operator: In
              values:
                - worker

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: mariadb-init-pvc
  name: mariadb-init-pvc
spec:
  accessModes:
    - ReadOnlyMany
  storageClassName: mariadb-init-storage
  resources:
    requests:
      storage: 1Mi
