apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    io.kompose.network/ticketing-ticketing-net: "true"
    io.kompose.service: mariadb
  name: mariadb
spec:
  serviceName: mariadb
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mariadb
  template:
    metadata:
      labels:
        io.kompose.service: mariadb
    spec:
      containers:
        - args:
            - --init-file
            - /data/init.sql
          env:
            - name: MARIADB_DATABASE
              value: ticketing
            - name: MARIADB_PASSWORD_FILE
              value: /run/secrets/mariadb_password
            - name: MARIADB_ROOT_PASSWORD_FILE
              value: /run/secrets/mariadb_root_password
            - name: MARIADB_USER
              value: ticketing
          image: mariadb
          name: mariadb
          ports:
            - containerPort: 3306
              hostPort: 3306
          volumeMounts:
            - mountPath: /run/secrets/mariadb_root_password
              name: mariadb_root_password
            - mountPath: /run/secrets/mariadb_password
              name: mariadb_password
            - mountPath: /var/lib/mysql
              name: ticketing-mariadb
            - mountPath: /data
              name: mariadb-claim1
      hostname: mariadb
      restartPolicy: OnFailure
      volumes:
        - name: mariadb_root_password
          secret:
            items:
              - key: mariadb_root_password
                path: mariadb_root_password
            secretName: mariadb_root_password
        - name: mariadb_password
          secret:
            items:
              - key: mariadb_password
                path: mariadb_password
            secretName: mariadb_password
        - name: ticketing-mariadb
          persistentVolumeClaim:
            claimName: ticketing-mariadb
        - name: mariadb-claim1
          persistentVolumeClaim:
            claimName: mariadb-claim1
