apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mariadb-local-storage
provisioner: kubernetes.io/no-provisioner
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: mariadb-pv
spec:
  capacity:
    storage: 100Mi
  volumeMode: FileSystem
  accessModes:
    - ReadWriteOnce
  storageClassName: mariadb-local-storage
  local:
    path: /mnt/c/temp/data/db/mariadb
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - docker-desktop

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: mariadb-claim1
  name: mariadb-claim1
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: mariadb-local-storage
  resources:
    requests:
      storage: 100Mi
