apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: postgres-data-storage
provisioner: kubernetes.io/no-provisioner
reclaimPolicy: Retain
volumeBindingMode: Immediate

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
spec:
  capacity:
    storage: 100Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: postgres-data-storage
  local:
    path: /data/db/postgres
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: node-role.kubernetes.io/worker
              operator: In
              values:
                - worker

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: postgres-data-pvc
  name: postgres-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: postgres-data-storage
  resources:
    requests:
      storage: 100Mi
