apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    kompose.cmd: /home/vezir/go/bin/kompose convert -f stack.yml
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: redis
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: redis
  template:
    metadata:
      annotations:
        kompose.cmd: /home/vezir/go/bin/kompose convert -f stack.yml
        kompose.version: 1.32.0 (HEAD)
      labels:
        io.kompose.network/ticketing-ticketing-net: "true"
        io.kompose.service: redis
    spec:
      containers:
        - args:
            - redis-server
            - --save
            - "60"
            - "1"
            - --loglevel
            - warning
          image: redis:7-alpine
          name: redis
          ports:
            - containerPort: 6379
              hostPort: 6379
          volumeMounts:
            - mountPath: /data
              name: redis-data
      hostname: redis
      restartPolicy: Always
      volumes:
        - name: redis-data
          persistentVolumeClaim:
            claimName: redis-data-pvc
