//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

pub use super::comments::Entity as Comments;
pub use super::preferences::Entity as Preferences;
pub use super::projects::Entity as Projects;
pub use super::ticket_attachments::Entity as TicketAttachments;
pub use super::ticket_updates::Entity as TicketUpdates;
pub use super::tickets::Entity as Tickets;
pub use super::users::Entity as Users;
