//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "priority")]
pub enum Priority {
    #[sea_orm(string_value = "Low")]
    Low,
    #[sea_orm(string_value = "Normal")]
    Normal,
    #[sea_orm(string_value = "High")]
    High,
    #[sea_orm(string_value = "Critical")]
    Critical,
}
